import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import {
  DocsBody,
  DocsDescription,
  DocsPage,
  DocsTitle,
} from "@/app/docs/_components/docs-page";
import { cn } from "@/lib/cn";
import {
  getMethodBadgeClassName,
  type LocalOpenAPISpecId,
  listLocalOperations,
  localOpenAPISpecs,
} from "@/lib/openapi";

interface ApiSpecPageProps {
  params: {
    schema: string;
  };
}

export default async function ApiSpecPage({ params }: ApiSpecPageProps) {
  const schemaId = params.schema as LocalOpenAPISpecId;
  const schema = localOpenAPISpecs[schemaId];

  if (!schema) {
    notFound();
  }

  const info = schema.info ?? {};
  const operations = listLocalOperations(schemaId);
  if (operations.length === 0) {
    notFound();
  }

  const description =
    typeof info.description === "string" ? info.description : undefined;

  return (
    <DocsPage>
      <DocsTitle>{info.title ?? schemaId}</DocsTitle>
      <DocsDescription>{description}</DocsDescription>
      <DocsBody className="flex flex-col gap-6">
        <p className="text-sm text-dashboard-zinc-400">
          Choose an operation to explore its autogenerated reference.
        </p>
        <div className="grid gap-4">
          {operations.map((operation) => (
            <OperationCard
              key={operation.slug}
              schemaId={schemaId}
              operation={operation}
            />
          ))}
        </div>
      </DocsBody>
    </DocsPage>
  );
}

export async function generateStaticParams() {
  return Object.keys(localOpenAPISpecs).map((schema) => ({ schema }));
}

export async function generateMetadata({
  params,
}: ApiSpecPageProps): Promise<Metadata> {
  const schemaId = params.schema as LocalOpenAPISpecId;
  const schema = localOpenAPISpecs[schemaId];
  if (!schema) return {};

  const info = schema.info ?? {};

  return {
    title: info.title ?? schemaId,
    description:
      typeof info.description === "string"
        ? info.description.split("\n").filter(Boolean)[0]
        : undefined,
  };
}

function OperationCard({
  schemaId,
  operation,
}: {
  schemaId: LocalOpenAPISpecId;
  operation: ReturnType<typeof listLocalOperations>[number];
}) {
  const title =
    operation.summary ??
    operation.operationId ??
    `${operation.method.toUpperCase()} ${operation.path}`;

  return (
    <Link
      href={`/apis/${schemaId}/${operation.slug}`}
      className="group rounded-2xl border border-dashboard-zinc-800/60 bg-dashboard-zinc-950/70 p-5 transition hover:border-dashboard-red-600/60 hover:bg-dashboard-zinc-900/60"
    >
      <div className="flex items-center justify-between gap-4">
        <div className="flex flex-col gap-1">
          <span className="text-sm font-medium text-dashboard-zinc-300 group-hover:text-dashboard-zinc-100">
            {title}
          </span>
          <span className="text-xs text-dashboard-zinc-500">
            {operation.description ??
              "View request and response details for this endpoint."}
          </span>
        </div>
        <span
          className={cn(
            "rounded-full border bg-dashboard-zinc-900/70 px-3 py-1 text-xs font-semibold uppercase tracking-wide",
            getMethodBadgeClassName(operation.method),
          )}
        >
          {operation.method.toUpperCase()}
        </span>
      </div>
      <span className="mt-4 inline-flex items-center gap-2 text-xs text-dashboard-zinc-500 group-hover:text-dashboard-zinc-300">
        <code className="rounded-full border border-dashboard-zinc-800/60 bg-dashboard-zinc-900/60 px-3 py-1">
          {operation.path}
        </code>
        <span aria-hidden="true">→</span>
      </span>
    </Link>
  );
}
