import type { Metadata } from "next";
import Link from "next/link";
import {
  DocsBody,
  DocsDescription,
  DocsPage,
  DocsTitle,
} from "../_components/docs-page";

export const metadata: Metadata = {
  title: "Getting Started",
  description:
    "Spin up the docs locally and keep the autogenerated API pages in sync.",
};

const installCmd = `pnpm install
npm install
yarn install
bun install`;

const devCmd = `pnpm dev
npm run dev
yarn dev
bun dev`;

export default function GettingStartedPage() {
  return (
    <DocsPage>
      <DocsTitle>Getting Started</DocsTitle>
      <DocsDescription>
        Everything you need to spin up Fumadocs locally, customize the UI, and
        keep the autogenerated API reference up to date.
      </DocsDescription>
      <DocsBody>
        <h2 id="prerequisites">Prerequisites</h2>
        <p>
          Make sure you have{" "}
          <Link href="https://nodejs.org/" target="_blank" rel="noreferrer">
            Node.js 18+
          </Link>{" "}
          installed. The project uses pnpm by default, but any modern package
          manager will work.
        </p>

        <h2 id="install-dependencies">Install dependencies</h2>
        <p>
          From the repository root, install dependencies with your tool of
          choice:
        </p>
        <pre>
          <code>{installCmd}</code>
        </pre>

        <h2 id="run-locally">Run the local docs site</h2>
        <p>
          Start the Next.js development server and open{" "}
          <code>http://localhost:3000</code> in your browser.
        </p>
        <pre>
          <code>{devCmd}</code>
        </pre>
        <p>
          The UI hot-reloads automatically. Edit components under{" "}
          <code>src/app/docs</code> or styles in <code>src</code> to customize
          the experience.
        </p>

        <h2 id="update-api-reference">Update the API reference</h2>
        <p>
          Run the generator whenever the OpenAPI schema changes. It rewrites the
          MDX pages under <code>content/docs</code>.
        </p>
        <pre>
          <code>pnpm tsx scripts/generate-docs.ts</code>
        </pre>
        <p>
          The autogenerated pages render through the{" "}
          <code>fumadocs-openapi</code> integration, so you never edit them by
          hand.
        </p>

        <h2 id="next-steps">Next steps</h2>
        <ul>
          <li>
            Tweak the sidebar and shell in{" "}
            <code>src/app/docs/_components/layout-client.tsx</code>.
          </li>
          <li>
            Swap out the default branding in <code>src/app/page.tsx</code> and{" "}
            <code>public/</code>.
          </li>
          <li>
            Add custom MDX guides alongside the API reference inside{" "}
            <code>content/docs</code>.
          </li>
        </ul>
      </DocsBody>
    </DocsPage>
  );
}
